### PR TITLE
Return null for golang zero dates

### PR DESCRIPTION
**Pull request by oponder**
Related to: https://github.com/giantswarm/webclient/issues/123

Also, I am tempted to immediately parse dates and return proper (moment.js) date objects right here
instead of the date string.

That way any client that depends on this libary will always get a proper date object
which it can depend on.

Something to consider!

### CODE REVIEW

**Comment by oponder** [comment]
Looks like this is now doing the right thing.

moment.js is getting the null, and displaying "invalid date", which is the standard text, but can be changed: See https://github.com/giantswarm/webclient/pull/135

screen shot 2015-10-22 at 14 32 56

**Comment by oponder** [comment]
rfr @marians

**Comment by marians** [comment]
I'd prefer showing `n/a`, since this is kind of the standard we now use everywhere when there is no data.

If you want to make moment.js a dependency of the js-client, I'd be fine with it. We are the main customer for the js-client. Probably won't hurt others either.

**Comment by oponder** [comment]
Yup, giantswarm/webclient#135 will make it show n/a instead of 'invalid date'

Making moment.js a dependency of the js-client will come later if some refactoring gets prioritised.

**Pull request merged**
