### PR TITLE
Adding callback for 401 responses

### PR DESCRIPTION
**Pull request by marians**
RFR @oponder

Allows to set a special callback function to be called when a 401 (Unauthorized) error is received. The webclient uses this to end the session.

### CODE REVIEW

**Comment by oponder** [comment]
Looks OK to me. Making a mental note of this though as an opportunity to refactor. I think ideally we'd have a function also just to check if the user's credentials are valid, that we can then call in the initialisation of webclient as a first step. But for now, being pragmatic: shipit! :shipit:

**Comment by marians** [comment]
Had to add some more stuff.

**Comment by marians** [comment]
Seems like we're fine for now. Merging.

**Comment by oponder** [comment]
:+1:

**Pull request merged**
